- hosts:
#  - service_group
#  - web_group
#  - gateway_group
  - all 
  remote_user: root
  gather_facts: false
  vars:
  - TaskName: copy_config
  roles:
  - role: "{{role_name}}"
    when: instance_id in instances
